spring:
  application:
    name: transaction-service
  liquibase:
    enabled: true
    change-log: classpath:/database/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bankdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIt=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

server:
  port: 8082
  servlet:
    context-path: /transaction


logging:
  level:
    liquibase: DEBUG
    io:
      r2dbc:
        h2: TRACE