spring:
  application:
    name: account-service
  liquibase:
    enabled: true
    change-log: classpath:/database/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bankdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIt=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

server:
  port: 8081
  servlet:
    context-path: /account

iban:
  country-code: PL
  bank-code: 191

service:
  transaction:
    url: http://localhost:8082/transaction

logging:
  level:
    liquibase: DEBUG
    io:
      r2dbc:
        h2: TRACE