spring:
  application:
    name: account-service
  r2dbc:
    url: r2dbc:h2:mem:///bankdb
    username: testuser
    password: O0xp5WnE7dqOkxQ
    properties:
      MODE: MySQL
      DB_CLOSE_DELAY: -1
      DB_CLOSE_ON_EXIT: FALSE
  liquibase:
    enabled: true
    change-log: classpath:/database/changelog/db.changelog-master.xml
  h2:
    console:
      enabled: true

server:
  port: 8081
  servlet:
    context-path: /account

iban:
  country-code: PL
  bank-code: 191

logging:
  level:
    liquibase: DEBUG
    io:
      r2dbc:
        h2: TRACE